export enum columnsDefinitions {
    ENROLLMENT_ID = 'pi',
    ORGUNIT_ID = 'ou',
    ORGUNIT_NAME = 'ouname',
    TEI = 'tei',
    FIRST_NAME = 'sB1IHYu2xQT',
    LAST_NAME = 'ENRjVGxVL6l',
    AGE = 'Rv8WM2mTuS5',
    SEX = 'oindugucx72',
    NATIONALITY = 'qlYg7fundnJ',
    TEST_PLATFORM = 'w9R4l7O9Sau',
    SPECIMEN_TYPE = 'kL7PTi4lRSl',
    SPECIMEN_ID = 'f48odhAyNtd',
    DATE_SPECIMEN_COLLECTED = 'Q98LhagGLFj',
    DATE_SPECIMEN_RECEIVED = 'RfWBPHo9MnC',
    SPECIMEN_CONDITION = 'P61FWjSAjjA',
    LAB_TEST_RESULT = 'ovY6E8BSdto',
    TEST_METHOD = 'b4PEeF4OOwc',
    DATE_RESULT_RELEASED = 'ZLEOP9JHZ5c'
}